# Generated by Django 5.0.3 on 2024-03-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_remove_tarea_estado_remove_tarea_nombre_tarea_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='correo',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='nombre_dueno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='telefono',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='equipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_mantenimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='procedimiento',
            field=models.TextField(),
        ),
    ]
