# Generated by Django 5.0.3 on 2024-03-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_tarea_correo_tarea_nombre_dueno_tarea_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='nombre_dueno',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='telefono',
        ),
    ]
